/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "rpc_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace rocksT {


RemoteCompactionJob::~RemoteCompactionJob() noexcept {
}

std::ostream& operator<<(std::ostream& out, const RemoteCompactionJob& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t RemoteCompactionJob::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    xfer += iprot->skip(ftype);
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t RemoteCompactionJob::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("RemoteCompactionJob");

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(RemoteCompactionJob &a, RemoteCompactionJob &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

RemoteCompactionJob::RemoteCompactionJob(const RemoteCompactionJob& other0) {
  (void) other0;
}
RemoteCompactionJob& RemoteCompactionJob::operator=(const RemoteCompactionJob& other1) {
  (void) other1;
  return *this;
}
void RemoteCompactionJob::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "RemoteCompactionJob(";
  out << ")";
}

} // namespace
